name: blog-compose
services:
  postgres:
    image: postgres:latest
    container_name: postgres_blog
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      -  postgres_blog_data:/var/lib/postgresql/data
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo_blog
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_blog_data:/data/db
    env_file:
      - .env

volumes:
  postgres_blog_data:
  mongo_blog_data:
